### ISSUE TITLE
It doesn't open after compiling No errors too.

### ISSUE THREAD

**Issue by WK-GiHu** [wan-joe/OPEN-TKINTER-APP-ONCE#13]
@wan-joe 

>It doesn't open after compiling
>No errors too.

Also not output  of

     print('PROCNAME:'...

or

    print('EXIT:'...

# ????

**Comment by wan-joe** [comment]
@WK-GiHu 

No output

**Comment by WK-GiHu** [comment]
@wan-joe 

> No output

You have `print(...` statements in your code, so there must at least the output of this.

Please confirm the following:
- [ ] I use the code as shown in [TKINETER AP ONCE](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/master/TKINETER%20APP%20ONCE)
- [ ] I have verified `myapp.py` works within `PyCharm` as expected, means **Run only once**!
- [ ] I have compiled this **working** `myapp.py` without `--windowed` option
- [ ] I have verified, the `myapp.exe` are the newest current compiled version
- [ ] I run it from the `command prompt` using `myapp.exe`

**Comment by wan-joe** [comment]
```
Traceback (most recent call last):
  File "myapp.py", line 30, in <module>
NameError: name 'exit' is not defined
```

after running it from `cmd`

**Comment by WK-GiHu** [comment]
@wan-joe 

**You didn't update the source at [TKINETER AP ONCE](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/master/TKINETER%20APP%20ONCE)**

- [ ] Update source

---


`NameError: name 'exit' is not defined`: should alread fixed, see [issuecomment-517772645](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/12#issuecomment-517772645)

**Comment by wan-joe** [comment]
have done that `sys.exit(None)` after that the it runs alright from the `cmd` but the `gui` doesn't display

This is the output from the cmd :


```
info:{'cmdline': ['taskhostw.exe'], 'pid': 12256, 'name': 'taskhostw.exe'}
info:{'cmdline': ['C:\\Users\\MAR-LAP1\\AppData\\Local\\Programs\\Python\\Python36\\pythonw.exe', '-m', 'idlelib', 'C:\\Users\\MAR-LAP1\\Desktop\\ONCE APP\\myapp.py'], 'pid': 12456, 'name': 'pythonw.exe'}
info:{'cmdline': ['C:\\Windows\\System32\\RuntimeBroker.exe', '-Embedding'], 'pid': 13196, 'name': 'RuntimeBroker.exe'}
info:{'cmdline': ['C:\\Windows\\System32\\RuntimeBroker.exe', '-Embedding'], 'pid': 14840, 'name': 'RuntimeBroker.exe'}
info:{'cmdline': ['C:\\Windows\\System32\\MicrosoftEdgeCP.exe', '-ServerName:Windows.Internal.WebRuntime.ContentProcessServer'], 'pid': 14896, 'name': 'MicrosoftEdgeCP.exe'}
info:{'cmdline': ['\\??\\C:\\WINDOWS\\system32\\conhost.exe', '0x4'], 'pid': 16068, 'name': 'conhost.exe'}
info:{'cmdline': ['C:\\Users\\MAR-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 16404, 'name': 'myapp.exe'}
EXIT:{'cmdline': ['C:\\Users\\MAR-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 16404, 'name': 'myapp.exe'}
PS C:\Users\MAR-LAP1\Desktop\ONCE APP\dist>
```

**Comment by WK-GiHu** [comment]
@wan-joe 

## Please, always show this info also:

  -  Show the output of ` print('PROCNAME:{} PID:{}'.format(PROCNAME, PID))`
  -  I also need to know **FIRST RUN** or **SECOND RUN**!!

---

> runs alright from the cmd but the gui doesn't display

Yes, this condition evaluates to `True`:

    if PROCNAME == info['name'] and PID != info['pid']:

but without the above informations i can't tell anything!!

**Comment by wan-joe** [comment]
@WK-GiHu 

 This is the output `PROCNAME:myapp.exe PID:17032`

First run

**Comment by wan-joe** [comment]
@WK-GiHu 

Any response ?

**Comment by WK-GiHu** [comment]
@wan-joe 

>This is the output `PROCNAME:myapp.exe PID:17032`

There is no `PID:17032` in your [***output from the cmd :***](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-523865385)
There is only:

    'pid': 16404, 'name': 'myapp.exe'}

therefore your output is not from the same run.

I need **ALL** three infos from **one run**:

1.  The output from the cmd : `info:{..., 'pid': 16404, 'name': 'myapp.exe'}`
2. The output of `print('PROCNAME:{} PID:{}'.format(PROCNAME, PID))`
3. `First run` or `Second run`

**Comment by wan-joe** [comment]
@WK-GiHu 

These are the outputs:

1. `info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 38616}`
2. `PROCNAME:myapp.exe PID:38664`
3. `First run output`

**Comment by WK-GiHu** [comment]
@wan-joe 

>... 'pid': 38616} ... PID:38664

The `pid` are different, therefore the condition can't be `True`.
You also don't get the output of `print('EXIT:...`


            if PROCNAME == info['name'] and PID != info['pid']:
                print('EXIT:{}'.format(proc.info))
                exit(0)

Conclusion, `exit(0)` does not prevent to call `start_app()`

---

### You haven't confirmed anything from this [comment](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-523840837), please do so.

**Comment by wan-joe** [comment]
@WK-GiHu 

`pid and PID`  are different even when i run the script without compiling 

This `print('EXIT:...` get printed .

You can run at your end to see the output.

**Comment by WK-GiHu** [comment]
@wan-joe 

>This `print('EXIT:...` get printed .

Your first [comment](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-523834422) stated contradict, which leads to wrong decicsion.

---

I need more info, please change the following:
```
        if info['cmdline']:
            if PROCNAME == info['name']:
                print('info:{}'.format(info))
        
            """
            Disabled, to allow Second run and show **ALL**
            if PROCNAME == info['name'] and PID != info['pid']:
                print('EXIT:{}'.format(proc.info))
                sys.exit(0)
            """
```
I need to see **ALL** `print('info:...` and  `PROCNAME:myapp.exe PID:???` from the **SECOND** run.

**Comment by wan-joe** [comment]
@WK-GiHu
Don't understand can you pull request so i can merge it.

**Comment by wan-joe** [comment]
This new results after the changes

`PROCNAME:myapp.exe PID:13292`

`info:{'name': 'myapp.exe', 'pid': 13292, 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe']}`

Then i found another result from myapp.exe  with this ouptput from same run

 `info:{'name': 'myapp.exe', 'pid': 16548, 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe']}`

**Comment by WK-GiHu** [comment]
@wan-joe 

>Then i found another result from myapp.exe with this ouptput from same run

The another result, is from:
- [x] First run
- [ ] Second run

---

Change the source again, see updated [comment](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-537008076)
I need to see ALL `print('info:..:` and `PROCNAME:myapp.exe PID:???` from the **FIRST** AND the **SECOND** run.  Please mark, which run  is wich!

**Comment by wan-joe** [comment]
**First run:**

`PROCNAME:myapp.exe PID:10924`
 
`info:{'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 10924, 'name': 'myapp.exe'}`

`info:{'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 22220, 'name': 'myapp.exe'}`

**Second run:**

`PROCNAME:myapp.exe PID:22352`

`info:{'pid': 22220, 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}`

`info:{'pid': 22352, 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}`

`info:{'pid': 22424, 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}`

`info:{'pid': 10924, 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe'}`


These are the results i get from the each run.

**Comment by WK-GiHu** [comment]
@wan-joe 

> These are the results i get from the each run.

This explains the behavior, you have to find the reason **WHY** the `myapp.exe` get startet **TWICE**.
There should be **only one** per run!

---

Show or explaine how do you start?
- [ ] Typed in terminal `myapp.exe` once.
- [ ] Click on Desktop symbol, once
- [x] Click on Desktop symbol, twice
- [ ] Other

**Comment by wan-joe** [comment]
first run = I mean when when i double click on app to open 

Second run = I don't close the app then i double click on it again to open.

**Comment by WK-GiHu** [comment]
@wan-joe 

OK, it seems there are child processes, we need more info to find the parent process:
Change the following:
```
for proc in psutil.process_iter(attrs=['pid', 'name', 'cmdline', 'parent', 'ppid']):
```
I need to see ALL `print('info:..` and `PROCNAME:myapp.exe PID:???` from the **FIRST AND** the **SECOND** run. Please mark, which run is wich!

**Comment by wan-joe** [comment]
@WK-GiHu

Getting error 

`ValueError: invalid attr name 'parent'`

**Comment by WK-GiHu** [comment]
@wan-joe 

>`ValueError: invalid attr name 'parent'`

Change to the following:

```
    for proc in psutil.process_iter(attrs=['pid', 'name', 'cmdline']):
        info = proc.info
        if PROCNAME == info['name']:
            print('info:{}, parent:{}, ppid:{}'.format(info, proc.parent(), proc.ppid()))
```

**Comment by wan-joe** [comment]
@WK-GiHu 

Only this get printed 

`PROCNAME:myapp.exe PID:19496`

Do pull request so i can merge it

**Comment by WK-GiHu** [comment]
@wan-joe 

> Do pull request so i can merge it

You have to update [TKINETER APP ONCE](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/master/TKINETER%20APP%20ONCE) first.

**Comment by wan-joe** [comment]
@WK-GiHu 

Getting this error ;

`NameError: name 'exit' is not defined`

Doing it `sys.exit(None)` doesn't work.

**Comment by WK-GiHu** [comment]
@wan-joe 

>`NameError: name 'exit' is not defined`

### You are using a outdated version, see https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-523862283

- [ ] Please use the version here from GitHub [TKINETER APP ONCE](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/master/TKINETER%20APP%20ONCE)
- [ ] Update with changes from this https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-537008076 - **comment the second part**
- [x] Update with changes from this https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-537671862 - **change `print(...`**
- [x] Copy the result back **here on GitHub**, so I can review your overall changes.

**Comment by wan-joe** [comment]
@WK-GiHu

Same error `NameError: name 'exit' is not defined` after the changes.


Have attached the script.
[myapp.txt](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/files/3728851/myapp.txt)

**Comment by WK-GiHu** [comment]
@wan-joe 

> Same error NameError: name 'exit' is not defined after the changes.

You didn't apply any changes, no checkmark checked and no update!

### Do ALL steps, according to the LIST in  https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-538054994 

### Please obey the **LAST** step, don't attach your changed version to a comment, copy instead  to: [TKINETER APP ONCE](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/blob/master/TKINETER%20APP%20ONCE)

**Comment by wan-joe** [comment]
@WK-GiHu 

Have done the changes review to see if it is correct.

**Comment by WK-GiHu** [comment]
@wan-joe 

> review to see if it is correct.

It's totaly broken, copy from the following links.

- [x] Still not done  https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/12#issuecomment-517772645
- [x] Still not done https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-537008076 - comment the second part
- [x] Run it and tell, what gives `print('info:{}...` https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/issues/13#issuecomment-537671862

**Comment by wan-joe** [comment]
@WK-GiHu 

Please can you do it at your end and update the script.

Am not getting you well

**Comment by WK-GiHu** [comment]
@wan-joe 

See my `[Pull request]`:

- [x]  merge the pull request.

**Comment by wan-joe** [comment]
@WK-GiHu 

These are the result below:

**First run**

```
procname result below:
PROCNAME:myapp.exe PID:38908
info:{'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe', 'pid': 38908}, parent:psutil.Process(pid=43488, name='myapp.exe', started='13:42:30'), ppid:43488

info:{'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'name': 'myapp.exe', 'pid': 43488}, parent:psutil.Process(pid=45724, name='powershell.exe', started='13:41:31'), ppid:45724

```

**Second run :**

```
procname result below:
PROCNAME:myapp.exe PID:42836
info:{'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 42092, 'name': 'myapp.exe'}, parent:psutil.Process(pid=45724, name='powershell.exe', started='13:41:31'), ppid:45724

info:{'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 42836, 'name': 'myapp.exe'}, parent:psutil.Process(pid=42092, name='myapp.exe', started='13:49:05'), ppid:42092


```

**Comment by WK-GiHu** [comment]
@wan-joe 

>These are the result below:
>Second run :

The ***Second run :***, is not the ***Second run :****, because there must be 4 lines of `info:..`
Please verify.

**Comment by wan-joe** [comment]
@WK-GiHu 


**First run :**

```
procname result below:
PROCNAME:myapp.exe PID:61104
info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 58724}, parent:psutil.Process(pid=62332, name='powershell.exe', started='12:25:55'), ppid:62332

info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 61104}, parent:psutil.Process(pid=58724, name='myapp.exe', started='12:26:40'), ppid:58724
```

**Second run:**

```
procname result below:
PROCNAME:myapp.exe PID:11948
info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 11948}, parent:psutil.Process(pid=60588, name='myapp.exe', started='12:28:36'), ppid:60588

info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 58724}, parent:psutil.Process(pid=62332, name='powershell.exe', started='12:25:55'), ppid:62332

info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 60588}, parent:psutil.Process(pid=5816, name='explorer.exe', started='08:48:03'), ppid:5816

info:{'name': 'myapp.exe', 'cmdline': ['C:\\Users\\MAR1-LAP1\\Desktop\\ONCE APP\\dist\\myapp.exe'], 'pid': 61104}, parent:psutil.Process(pid=58724, name='myapp.exe', started='12:26:40'), ppid:58724
```

**Comment by wan-joe** [comment]
@WK-GiHu 

Any update from you.

**Comment by WK-GiHu** [comment]
@wan-joe 

>Any update from you.

See my [`[Pull Request]`](https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/pull/15)

**Comment by wan-joe** [comment]
@WK-GiHu

Am getting this error

 ```
   name = proc.parent()['name']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by WK-GiHu** [comment]
@wan-joe 

Fixed: Merge from https://github.com/wan-joe/OPEN-TKINTER-APP-ONCE/pulls

**Comment by wan-joe** [comment]
@WK-GiHu 

```
    parent.add(proc.pid)
AttributeError: 'NoneType' object has no attribute 'add'
```

Getting another error.
